version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:10000
      - REDIS_URL=redis://redis:6379

  identity-service:
    build: ./services/identity-service
    environment:
      - REDIS_URL=redis://redis:6379

  reservation-service:
    build: ./services/reservation-service
    environment:
      - REDIS_URL=redis://redis:6379
