services:
  - type: redis
    name: shared-redis
    ipAllowList: []

  - type: web
    name: gateway
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gateway/main.py
    envVars:
      - key: IDENTITY_SERVICE_URL
        fromService: { name: identity-service, type: web, property: host }
      - key: RESERVATION_SERVICE_URL
        fromService: { name: reservation-service, type: web, property: host }

  - type: web
    name: identity-service
    env: python
    startCommand: uvicorn services.identity-service.src.app:app --host 0.0.0.0 --port 10000

  - type: web
    name: reservation-service
    env: python
    startCommand: uvicorn services.reservation-service.src.app:app --host 0.0.0.0 --port 10000

  - type: worker # Finance Service arka planda çalışır
    name: finance-worker
    env: python
    startCommand: python services/finance-service/src/worker.py
